-- Your SQL goes here
CREATE OR REPLACE FUNCTION ARRAY_TO_STRING_IMMUTABLE (
    arr TEXT[],
    sep TEXT
) RETURNS TEXT
IMMUTABLE
PARALLEL SAFE
LANGUAGE SQL AS $$
    SELECT ARRAY_TO_STRING(arr, sep)
$$;
